FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["ByteMeLogistics.Api.csproj", "."]

RUN dotnet restore "ByteMeLogistics.Api.csproj"

COPY . .

RUN dotnet build "ByteMeLogistics.Api.csproj" \
    -c Release \
    -o /app/build

FROM build AS publish

RUN dotnet publish "ByteMeLogistics.Api.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ByteMeLogistics.Api.dll"]