FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["BYTE_ME_CoffeeNChill.csproj", "./"]

RUN dotnet restore "BYTE_ME_CoffeeNChill.csproj"

COPY . .

RUN dotnet publish "BYTE_ME_CoffeeNChill.csproj" \
    -c Release \
    -o /home/site/wwwroot \
    /p:UseAppHost=false


FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0

ENV AzureWebJobsScriptRoot=/home/site/wwwroot

ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=build /home/site/wwwroot /home/site/wwwroot